### ISSUE TITLE
macOS No Sensors Found

### ISSUE THREAD

**Issue by Walther** [ClementTsang/bottom#371]
## Describe the bug

on macOS, `btm` reports No Sensors Found in the temperature block.

## To reproduce

1. Run `btm` on macOS
2. Observe the `No Sensors Found` message

## bottom version

`bottom 0.5.5`

## bottom config file (if used)

no config file

## Installation method

homebrew

```
brew info bottom
clementtsang/bottom/bottom: stable 0.5.5
A cross-platform graphical process/system monitor with a customizable interface and a multitude of features.
https://github.com/ClementTsang/bottom
/usr/local/Cellar/bottom/0.5.5 (5 files, 3.4MB) *
  Built from source on 2020-12-16 at 23:09:06
From: https://github.com/clementtsang/homebrew-bottom/blob/HEAD/bottom.rb
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
```

### Operating system, OS version, and architecture

macOS Big Sur 11.1 (20C69)

### Terminal (i.e. urxvt, kitty, etc.)

`alacritty`

### Shell (i.e. zsh, bash, etc.)

`zsh`

### Miscellaneous system info

macbook pro 15" 2018, 6-core i7, radeon 560X, 16GB ddr4, 512GB ssd

**Comment by ClementTsang** [comment]
Please update to [0.5.6](https://github.com/ClementTsang/bottom/releases/tag/0.5.6).  This has a fix for the issue.

**Comment by ClementTsang** [comment]
Closing for now, this should already be resolved.  Feel free to reopen if not.

**Comment by sourTaste000** [comment]
issue still appears on version 0.5.6.

### brew version
```
clementtsang/bottom/bottom: stable 0.5.6
A cross-platform graphical process/system monitor with a customizable interface and a multitude of features.
https://github.com/ClementTsang/bottom
/usr/local/Cellar/bottom/0.5.6 (5 files, 3.4MB) *
  Built from source on 2021-01-02 at 10:44:01
From: https://github.com/clementtsang/homebrew-bottom/blob/HEAD/bottom.rb
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
```
___
### System info
```
sourtaste000@coconut.local 
-------------------------- 
OS: macOS Big Sur 11.0.1 20B29 x86_64 
Host: MacBookPro17,1 
Kernel: 20.1.0 
Shell: zsh 5.8 
Terminal: kitty 
CPU: VirtualApple (8) @ 2.50GHz processor 
GPU: Apple M1 
```

**Comment by ClementTsang** [comment]
@sourTaste000 Not sure if that's an issue with the M1 processor in tandem with the libraries I work with... it works fine for me on a Catalina Hackintosh, and correctly shows the CPU temps.

I also don't own an M1 Mac or anything running Big Sur, unfortunately, so I can't really test it here...

If possible, could you:

1.  Go to https://github.com/GuillaumeGomez/sysinfo and clone the repo
2. `cd` into the repo go to `examples`, then run `cargo run`
3. Type "temperature" in the program that runs and tell me the output?

That might help me determine if it's an issue with the library or my program.

Thanks!

**Comment by sourTaste000** [comment]
it does not return anything.

**Comment by ClementTsang** [comment]
Yeah... if that's the case then it's an upstream issue with sysinfo, and I can't really do much.

I'm guessing the library just doesn't support M1 and/or Big Sur yet?  Unfortunately if that's the case then I'll also have to mark the current support for bottom on it to be incomplete as well.

**Comment by ClementTsang** [comment]
Going to close this issue and open a new one specifically in regards to M1 support, but I don't expect to be able to do much on it for now.

https://github.com/ClementTsang/bottom/issues/382
